name: Deploy ResumeAnalyzer to VPS

on:
  push:
    branches: [ "release" ]   # Deploy when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ResumeAnalyzer/ResumeAnalyzer.csproj

      # 4. Build
      - name: Build project
        run: dotnet build ResumeAnalyzer/ResumeAnalyzer.csproj --configuration Release --no-restore

      # 5. Publish
      - name: Publish project
        run: dotnet publish ResumeAnalyzer/ResumeAnalyzer.csproj -c Release -o ./publish

      # 6. Upload files to VPS
      - name: Upload published files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ResumeAnalyzer_VPS_HOST }}
          username: ${{ secrets.ResumeAnalyzer_VPS_USER }}
          key: ${{ secrets.ResumeAnalyzer_VPS_SSH_KEY }}
          source: "publish/*"
          target: "/home/${{ secrets.ResumeAnalyzer_VPS_USER }}/apps/ResumeAnalyzer"

      # 7. Restart service on VPS
      - name: Restart ResumeAnalyzer service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl restart resumeanalyzer
